version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es-container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  node:
    build: .
    container_name: node-container
    depends_on:
      - elasticsearch
